### ISSUE TITLE
🧨Dynamics - Skills filtering is starts with instead of contains

### ISSUE THREAD

**Issue by pierssinclairssw** [SSWConsulting/SSW.People#375]
cc @ozdemir-mehmet, @leahy268

Hi @drwharris ,

As per our conversation with @adamcogan @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @JeanThirion SSW people skills are stored in Dynamics365 but the filtering process makes it difficult to find skills when you search for them.

- [ ] Change the filter from a **starts with** to a **contains** search

![DynamicsSearching1](https://user-images.githubusercontent.com/79821522/151749916-152bbfc9-60f8-4d87-8ba5-2a187b607017.png)
**Figure: When I search for SQL I can see SQL Server**

![DynamicsSearching2](https://user-images.githubusercontent.com/79821522/151749921-d3d85c5c-8b11-4c81-b1df-bd13e1b14b54.png)
**Figure: When I search for Server I see nothing but I should see SQL Server**

**Comment by drwharris** [comment]
CC @christianmorfordwaitessw @UlyssesMaclaren @calumjs @brydeno @JeanThirion @ozdemir-mehmet @leahy268

Hi @adamcogan 

In discussion with @calumjs this form is an out of the box dynamics form which makes the job of customising harder. Calum has however pointed out that you can use wildcards, eg *server acts as a contains instead of starts with.

I have updated SugarLearning item https://my.sugarlearning.com/SSW/items/13213/crm-add-your-details-to-crm-for-your-public-ssw-people-profile-and-ssw-sophiebot with an information box pointing this out. 

![image](https://user-images.githubusercontent.com/19632724/152102105-9ba26eab-c1d3-497a-9eae-c4ef43ae0cd0.png)
Figure: New Informational box

I have also spoken to @jaydenalchin about updating the relevant image to show this functionality. He has said it should be relatively simple. 

Given the complexities around changing out of the box screens and the ongoing issues that creates, eg upgrade complexity, upgrades that overwrite your changes, etc, are we better off going down a path of education like the SugarLearning changes instead?

**Comment by JackDevAU** [comment]
Closing stale issue. 

Hey @drwharris 

1. Please reopen after following up with Adam
