### ISSUE TITLE
💄Add a HR separator between logo's and content

### ISSUE THREAD

**Issue by Geordie88** [SSWConsulting/SSW.People#422]
cc: @adamcogan, @bradystroud, @tiagov8 

Hi @christianmorfordwaitessw 

I got a task from Tiago to add a new hr separating the logos and content of people's pages.
![image](https://user-images.githubusercontent.com/97079655/181431153-c72c8d8b-2b42-4060-90e7-4900aea0bd68.png)
figure: where to add hr

After looking into the matter and consulting with Brady I confirmed that I would have to change elements of the assembly code. This is a dev task rather than a design one.

---

1.  Add a hr between the logos and content in SSW.People

**Comment by JackDevAU** [comment]
Hi @tiagov8 

1. Please reopen if this is still something you want

**Comment by tiagov8** [comment]
Still wanted

**Comment by JackDevAU** [comment]
Hey @tiagov8 

I'm closing this issue as a "won't do" due to the limitations of the current implementation. 

After a look at how this page is working - the badges + content all come in from markdown. So as of right now there isn't an easy solution to this problem. The only way (without pain and sadness) to add a `<hr>` would be in the markdown. 

Just as @Marxoz has done: 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/9568562a-8c80-4113-8215-1474378acb17)
**Figure: Gert's People profile - https://www.ssw.com.au/people/gert-marx/**

**Comment by tiagov8** [comment]
Hi @JackDevAU 

FYI - I added a "Note" here: https://github.com/SSWConsulting/SSW.People.Profiles/wiki/6.-Extras-%E2%80%90-Editing-profiles#extra---badges
