### ISSUE TITLE
Badges should allow rectangles

### ISSUE THREAD

**Issue by sethdailyssw** [SSWConsulting/SSW.People#499]
@wicksipedia as per our conversation, SSW.People.Profiles  should allow rectangular badges (currently it only allows squares). Some of the Microsoft badges which are rectangles have to be zoomed out to fit. Then they are too small to read!

![image](https://github.com/SSWConsulting/SSW.People/assets/130118701/c81df6e5-fc25-4ce0-a085-a3366fb9a6f9)
Figure: Can’t read Microsoft POTY badge
 
![image](https://github.com/SSWConsulting/SSW.People/assets/130118701/6da478e6-8ace-49dd-a51b-39f49ddbe4c0)
Figure: The square requirement in GitHub

1.	Please change this to allow rectangle shaped badges
            •	It can be any shape, or a designated rectangle size e.g. 202x135px
            •	Here is an example of a rectangle badge [POTY-Finalist-badge-both.png (1768×1145) (sharepoint.com)](https://sswcom.sharepoint.com/sites/SSWMarketing/Shared%20Documents/General/Microsoft%20POTY%20Awards%202023/finalist-assets/POTY-Finalist-badge-both.png?csf=1&web=1&e=425XLD&cid=3fc8e063-e3f9-4b39-8be3-1e47699dc597)

@camillars @bradystroud @UlyssesMaclaren

**Comment by wicksipedia** [comment]
Hey @sethdailyssw, I've had a look into this - there's no technical reason for the images to be square. I think there was an aesthetic decision to put that in the wiki - so it all looked consistent.

That being said - there are 3 options to move forward:

Option 1. (recommended) Photoshop the badge to be square - since this is the only rectangluar badge, it may make more sense to squarify it... it would look something like:
<img width="265" alt="CleanShot 2023-07-19 at 18 18 30@2x" src="https://github.com/SSWConsulting/SSW.People/assets/600044/5b5665d8-4aa2-412f-b315-aba1cd6ec50a">

Option 2. Change the wiki to be more permissive - e.g. we prefer square images (height = 135px) but you can have it a little rectangular. This has the risk that images won't be aligned nicely

<img width="1149" alt="CleanShot 2023-07-19 at 18 23 46@2x" src="https://github.com/SSWConsulting/SSW.People/assets/600044/943da8ec-1a2b-4402-98dd-19ddf655b210">
Figure: badges wouldn't line up nicely like this

Option 3. Do nothing/leave the badge as is - rectangular badges still need to have some transparent padding to make them look square. There are other badges that are slightly rectangular (so you don't notice it as much) but this one is more obvious

**Comment by sethdailyssw** [comment]
❌ Option 1 (Squarify the rectangle badges) - We follow Microsoft's guidelines when using their media, and they don't allow cropping. If it weren't for that, this would be the best idea.

✅ Option 2 (Change the wiki to allow rectangles) - Let's proceed with this. If the alignment looks horrible, we can think of options:
     - Regulate the width of the rectangles and make sure they are above and below each other
     - Only put rectangles at the end
     - Have a rectangles and then squares on a new line
     - etc.

❌ Option 3 (Leave as is) - The rectangles have to be zoomed out and some of them are too small to read. Some still look ok but with others, including the important Microsoft ones, it is a problem and it looks unprofessional.

**Comment by wicksipedia** [comment]
Done - I've updated the wiki and closing this issue

![CleanShot 2023-07-20 at 10 05 24](https://github.com/SSWConsulting/SSW.People/assets/600044/252f5295-cf75-4c84-b16a-86c556287bbf)


@sethdailyssw you can upload a different version of the badge without the padding 🏆
