### ISSUE TITLE
💄STYLE - The Widget heading is inconsistent

### ISSUE THREAD

**Issue by JackDevAU** [SSWConsulting/SSW.People#545]
CC @adamcogan @jaydenalchin @tiagov8 @BrookJeynes @bradystroud 

Hi Team, 

The Widgets heading seems inconsistent.

### Tasks 

- [ ] Increase the size of the heading
- [ ] Change the colour to match the other headings 

### Screenshots 

![image](https://github.com/SSWConsulting/SSW.People/assets/57518417/b5e30d24-4377-43f6-a5ea-70e70bf55030)
**Figure: "Latest Rules" heading is inconsistent**

**Comment by tiagov8** [comment]
cc @jaydenalchin 

Hi @JackDevAU 

Because the "Latest Rules" widget title is part of the sidebar, I don't think it needs to be consistent with the headings inside the content. 

The suggested change would improve the mobile view,  but worsen the desktop view IMO

I agree on mobile the sections look cluttered. My suggestion would be to simply add a new `<hr />` before the widget:

<img width="441" alt="Screenshot 2023-10-10 at 10 07 14 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/b893d214-c046-4169-b445-6a380f910b4f">

**Comment by jaydenalchin** [comment]
> Because the "Latest Rules" widget title is part of the sidebar, I don't think it needs to be consistent with the headings inside the content.
> The suggested change would improve the mobile view, but worsen the desktop view IMO

+1 to @tiagov8 's point here. 

An alternate solution could be to move the Rules widget out of the sidebar (mobile + desktop) so all of this content is consistent & keeps consistency across those breakpoints.

**Comment by tiagov8** [comment]
> An alternate solution could be to move the Rules widget out of the sidebar (mobile + desktop) so all of this content is consistent & keeps consistency across those breakpoints.

Not a big fan of this solution... I think in terms of content, the current flow looks better. Moving a section from sidebar to main area would increase scrolling on desktop.

In fact one thing I would like to see is a slightly larger sidebar, but I guess that is for SSW.People v2

**Comment by JackDevAU** [comment]
Hey @tiagov8 

1. Please "test please" 
https://staging.ssw.com.au/people/jake-bayliss/

**Comment by tiagov8** [comment]
> 1. Please "test please"

Test pass ✅
