### ISSUE TITLE
🐛 BUG - Email link on SSW.People profiles does nothing...

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#575]
cc @adamcogan @bradystroud @christianmorfordwaitessw 

Hi team, 

Seems like the "Email" link on [a profile](https://www.ssw.com.au/people/adam-cogan/) doesn't work...

- [ ] 1. Please investigate and fix

<img width="700" alt="Screenshot 2023-12-27 at 9 26 01 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/9bc3c54f-01c0-4a82-bf1a-8a33f5988114">

**Comment by JackDevAU** [comment]
Hey @tiagov8,

What should the email be for this? 
Do we want this to be a persons SSW email? e.g. `bobnorthwind@ssw.com.au`

**Comment by tiagov8** [comment]
> Hey @tiagov8,
> 
> What should the email be for this? Do we want this to be a persons SSW email? e.g. `bobnorthwind@ssw.com.au`

Correct. It should be their SSW email.

**Comment by Aibono1225** [comment]
Hi @tiagov8 ,

After some investigations, I've just found that this feature has already been implemented in this PR: https://github.com/SSWConsulting/SSW.People/pull/164. 😵

It is not working as expected for some people because the default email handler is not configured correctly on the client side.
Can you try **changing your default `MailTo Protocol` to the email app you use**, like this:
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/a6cdb47b-3475-40c8-9666-3403f5ff5fdb)


Afterwards the email link should be working normally🙂.

**Comment by tiagov8** [comment]
Hi @Aibono1225 

We can't rely on client settings for a public website link to work.

- [ ] 1. Can we implement the "mailto" to the code so it works for everyone?
- [ ] 2. If not, can you discuss with the team if we should remove the Email link from profiles? I rather not have than have it broken

**Comment by Aibono1225** [comment]
cc: @JackDevAU @BrookJeynes 

Hi @tiagov8 ,

> Can we implement the "mailto" to the code so it works for everyone?

We've already implemented "Mailto" in the [code](https://github.com/SSWConsulting/SSW.People/blob/3ab79e1552e07c298ffcf586f94dba91bd7a1368/src/components/social-links/social-links.js#L38) (the email is not shown on the page because it has been encoded). Normally, when you click on 'Email', it opens a window for sending an email to, for example, `bobnorthwind@ssw.com.au` 


https://github.com/SSWConsulting/SSW.People/assets/127192800/c6860577-1d57-4c57-8f14-4902d4a330ad



As I mentioned, this won't work for people who don't have a working default MailTo Protocol. So for them clicking on the email link won't do anything. 🙁


> If not, can you discuss with the team if we should remove the Email link from profiles? I rather not have than have it broken

Yes, I'll follow up on this after the discussion. 🙂

**Comment by adamcogan** [comment]
Hi @Aibono1225 
I would not remove this because it works on most peoples PCs. You need to add some help text that links to a page on how to configure their MailTo link. 

So I would change
✉️ Email
to
✉️ Email  (_Having problems?_)
-a

**Comment by Aibono1225** [comment]
> Do we have a preset "subject" for this mailto? If not, can you please add one... E.g. "Contacting {{ EMPLOYEE NAME }} via SSW.People profile"

Done - Subject added and live now:
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/b6af0cc0-8d47-4ef1-a1ff-6a76314c77fc)

> Do we have any sort of anti-spam protection to these emails' links?

Yes, we have encoded the email address to hide it in the source code. This helps to reduce spams to some extent.

**Comment by Aibono1225** [comment]
Closing as this is done via https://github.com/SSWConsulting/SSW.People/pull/615

![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/45155c9e-6012-4fb0-bbbf-5a36ea73b227)
