### ISSUE TITLE
🐛 BUG - Headings lost their font-size style

### ISSUE THREAD

**Issue by tiagov8** [SSWConsulting/SSW.People#610]
cc @adamcogan @Aibono1225 

Hi team, 

today I looked at https://ssw.com.au/people/adam-cogan/ and headings are in a small font. Headings are set to have their font sizes to inherit...

- [ ] 1. What/Who caused this?
- [ ] 2. Please investigate and fix

<img width="864" alt="Screenshot 2024-02-21 at 10 07 43 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/c4e6fd57-f5d8-4d81-9a52-4a534b47d15e">

**Figure: "Skills" (h2) should be bigger and "Adam Cogan" (h1) should be even bigger**

<img width="563" alt="Screenshot 2024-02-21 at 10 10 44 AM" src="https://github.com/SSWConsulting/SSW.People/assets/12601228/b80a4a80-e540-43a6-bd55-c4dae3e0d5c2">

**Figure: CSS that causes this**

**Comment by Aibono1225** [comment]
Cc: @JackDevAU @bradystroud @BrookJeynes 

Hi @tiagov8 ,
>  What/Who caused this?

This is caused by a global css collision introduced in this [PR](https://github.com/SSWConsulting/SSW.People/pull/603)

> Please investigate and fix

Done - please see below:
![image](https://github.com/SSWConsulting/SSW.People/assets/127192800/8f447488-ac4b-4c47-bcfb-b47cb79f9d28)
